# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: sdk-release
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcu-sdk-github-release.git
      revision: release/2.16.000_major_rfp
      import:
        file: west.yml
        name-allowlist:
          - mcux-sdk
          - FreeRTOS-Kernel
          - CMSIS_5
          - mcux-sdk-middleware-sdmmc
          - mcux-sdk-middleware-connectivity-framework
          - fatfs
          - mcux-sdk-middleware-edgefast-bluetooth
          - mcux-sdk-middleware-ethermind
          - mbedtls
          - lwip
          - littlefs
          - mcuboot
          - mcux-sdk-examples
          - wifi_nxp
          - mcux-sdk-middleware-bluetooth-controller
          - mcux-sdk-middleware-bluetooth-host
          - mcux-sdk-middleware-ieee_802.15.4
          - mcux-sdk-middleware-multicore
          - mcux-sdk-middleware-usb
          - rpmsg-lite
          - secure-subsystem
        path-prefix: repo
