# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: sdk-release
      url: https://github.com/nxp-mcuxpresso/mcux-sdk.git
      revision: MCUX_2.16.100_QP2
      path: core
      import:
        name-allowlist:
          - mcux-sdk
          - FreeRTOS-Kernel
          - CMSIS_5
          - mcux-sdk-middleware-sdmmc
          - fatfs
          - mcux-sdk-middleware-edgefast-bluetooth
          - mcux-sdk-middleware-ethermind
          - mcux-sdk-middleware-connectivity-framework
          - mbedtls
          - lwip
          - littlefs
          - mcuboot
          - mcux-sdk-middleware-bluetooth-controller
          - mcux-sdk-middleware-bluetooth-host
          - mcux-sdk-middleware-ieee_802.15.4
          - mcux-sdk-middleware-multicore
          - mcux-sdk-middleware-usb
          - rpmsg-lite
          - mcux-secure-subsystem
          - wifi_nxp
        path-prefix: repo
    - name: mcux-sdk-examples
      url: https://github.com/nxp-mcuxpresso/mcux-sdk-examples.git
      revision: MCUX_2.16.100
      path: repo/examples
      groups:
        - groupSdkExample
  group-filter: [-groupSdkExample]