# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: sdk-release
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcu-sdk-github.git
      revision: sdk_2.16.0-rw-nbu-update
      path: core
      import:
        name-allowlist:
          - mcux-sdk
          - FreeRTOS-Kernel
          - CMSIS_5
          - mcux-sdk-middleware-sdmmc
          - fatfs
          - mcux-sdk-middleware-edgefast-bluetooth
          - mcux-sdk-middleware-ethermind
          - mbedtls
          - lwip
          - littlefs
          - mcuboot
          - mcux-sdk-examples
          - wifi_nxp
          - mcux-sdk-middleware-bluetooth-controller
          - mcux-sdk-middleware-bluetooth-host
          - mcux-sdk-middleware-ieee_802.15.4
          - mcux-sdk-middleware-multicore
          - mcux-sdk-middleware-usb
          - rpmsg-lite
          - mcux-secure-subsystem
        path-prefix: repo
    - name: mcux-sdk-middleware-connectivity-framework
      url: https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-connectivity-framework.git
      revision: MCUX_2.16.000_UpdRev0
      path: repo/middleware/wireless/framework
