/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef RT1170_MATTER_MBEDTLS_CONFIG_H
#define RT1170_MATTER_MBEDTLS_CONFIG_H

/* MBEDTLS_PSA_CRYPTO_C required MBEDTLS_CTR_DRBG_C or MBEDTLS_HMAC_DRBG_C or MBEDTLS_ENTROPY_C or MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG */
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_NO_PLATFORM_ENTROPY

#define MBEDTLS_CTR_DRBG_C

#endif // RT1170_MATTER_MBEDTLS_CONFIG_H