# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: core
      url: https://github.com/nxp-mcuxpresso/mcux-sdk.git
      revision: MCUX_2.15.000_RW610_K32W1
      import:
        name-allowlist:
          - CMSIS_5
          - fatfs
          - FreeRTOS-Kernel
          - littlefs
          - lwip
          - mbedtls
          - mcuboot
          - mcux-sdk-examples
          - mcux-sdk-middleware-bluetooth-controller
          - mcux-sdk-middleware-bluetooth-host
          - mcux-sdk-middleware-connectivity-framework
          - mcux-sdk-middleware-edgefast-bluetooth
          - mcux-sdk-middleware-ethermind
          - mcux-sdk-middleware-ieee_802.15.4
          - mcux-sdk-middleware-multicore
          - rpmsg-lite
          - mcux-secure-subsystem
          - wifi_nxp
        path-prefix: repo/sdk-2.15