# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: mcuxsdk_manifest
      url: https://github.com/nxp-mcuxpresso/mcuxsdk-manifests
      revision: release/connectivity_stable
      import:
        name-allowlist:
          - core 
          - freertos-kernel
          - mcux-freertos-drivers
          - mcux-devices-wireless
          - CMSIS
          - mcux-sdk-middleware-sdmmc
          - fatfs
          - ethermind
          - mcux-sdk-middleware-connectivity-framework
          - mbedtls
          - lwip
          - littlefs
          - ble_controller
          - bluetooth
          - edgefast_bt_ble
          - ieee-802.15.4
          - mcux-sdk-middleware-multicore
          - usb
          - rpmsg-lite
          - secure-subsystem
          - wifi_nxp
          - fw_bin
          - mcu-sdk-components
          - mcu-sdk-examples
          - els_pkc
          - mcux-devices-rt
          - mcux-devices-mcx
          - mcux-mcmgr
          - erpc
          - usb
          - mcuboot_opensource
        path-prefix: repo
    - name: bifrost
      url: https://github.com/nxp-zephyr/bifrost
      revision: main
      path: repo/bifrost
