# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
    projects:
        - name: mcuxsdk_manifest
          url: https://github.com/nxp-mcuxpresso/mcuxsdk-manifests
          revision: v25.03.00
          import:
              name-allowlist:
                  - core
                  - freertos-kernel
                  - mcux-freertos-drivers
                  - mcux-devices-wireless
                  - CMSIS
                  - mcux-sdk-middleware-sdmmc
                  - fatfs
                  - ethermind
                  - mbedtls
                  - lwip
                  - littlefs
                  - ble_controller
                  - bluetooth
                  - edgefast_bt_ble
                  - ieee-802.15.4
                  - mcux-sdk-middleware-multicore
                  - usb
                  - rpmsg-lite
                  - secure-subsystem
                  - wifi_nxp
                  - wpa_supplicant-rtos
                  - fw_bin
                  - mcu-sdk-components
                  - mcu-sdk-examples
                  - els_pkc
                  - mcux-devices-rt
                  - mcux-devices-mcx
                  - mcux-mcmgr
                  - erpc
                  - usb
                  - mcuboot_opensource
              path-prefix: repo
        - name: mcux-sdk-middleware-connectivity-framework
          url: https://github.com/nxp-mcuxpresso/mcuxsdk-middleware-connectivity-framework
          revision: fe4ff8e39fbfda6f4c657a6df67a266cb06ed0fc
          path: repo/mcuxsdk/middleware/wireless/framework
        - name: bifrost
          url: https://github.com/nxp-zephyr/bifrost
          revision: main
          path: repo/bifrost
          groups:
              - bifrost
group-filter: [-bifrost]
