# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  projects:
    - name: sdk-release
      url: https://github.com/nxp-mcuxpresso/mcux-sdk.git
      revision: MCUX_2.15.100
      path: core
      import:
        name-allowlist:
          - mcux-sdk
          - FreeRTOS-Kernel
          - CMSIS_5
          - mcux-sdk-middleware-sdmmc
          - mcux-sdk-middleware-connectivity-framework
          - fatfs
          - mcux-sdk-middleware-edgefast-bluetooth
          - mcux-sdk-middleware-ethermind
          - mbedtls
          - lwip
          - littlefs
          - mcuboot
          - mcux-sdk-examples
          - wifi_nxp
        path-prefix: repo/sdk-2.15
